### ISSUE TITLE
Add-to-app的MethodCallHandler不生效抛MissingPluginException解决一文遇到的疑惑

### ISSUE THREAD

**Issue by liguobing** [peterlpt/flutter_add-to-app_bugfix#1]
首先送上诚挚的感谢，您这篇文章解决了困扰了我好几天的问题。
我是 Flutter 初学者，按照官方文档操作了无数遍都失败，百度谷歌搜索了无数遍，也都是旧版本的操作方式。
最终看到了您的答案，帮助我完成了从 Flutter 端启动原生 Activity 的问题，太感谢了。

但还有一个疑惑，使用您的方法，原生 Activitty 该如何给 Flutter 传递数据呢？
举个例子：
原生 Activity（MainActivity） 有一个输入框（EditText）和一个按钮（Button）
点击按钮，获取输入框的数据传递到 Flutter 页面显示
因为使用了 BridgeActivity 来启动 Flutter，MethodChannel 以及 method 都是在 BridgeActivity 中定义的，
那么在 MainActivity 中该如何在跳转到 Flutter 的时候进行这个数据传递呢？

我现在的做法是在 BridgeActivity 中创建一个“static Object shareObject”，在点击按钮时，为这个 Object 对象赋值，并创建相应的 "shareData" 方法
在 Flutter 页面中的 initState 方法中通过通道调用这个 shareData 方法并回传 shareObject。

但我总感觉这个方法有点儿歪门邪道，请问您有更好的方法吗？

不甚感谢

**Comment by peterlpt** [comment]
客气了。
传递数据我知道的有两种方式可以参考：
方式一：将参数以链接URL查询参数形式拼接于初始化路由，再进入Flutter，再在dart端定义路由表，解释路由取参：

```java
Intent intent = BridgeActivity
        .withNewEngine()
        .initialRoute(initialRoute) //如：yourRouteName?param1=value1&param2=value2
        .build(MainActivity.this);
startActivity(intent);
```

`main.dart`参考：

```dart
class MyApp extends StatelessWidget {
  MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      //不要定义初始化路由及home，让MaterialApp从onGenerateRoute路由表中找路由
      //initialRoute: initialRoute,
      //home: ,
      onGenerateRoute: (settings) {
        //settings.name即为从HostApp传递过来的带参路由，如：yourRouteName?param1=value1&param2=value2
        //再根据需要，解释链接查询参数如为params, 进行页面选定跳转
        return MaterialPageRoute(builder: (context) => YourFlutterPage(params));
      },
    );
  }
 }
```

注意，这方法在你如果使用了预热的引擎是无效的。

方法二：使用MethodChannel，定义一个或共用现在这个，在dart端类似在HostApp端对其设置好`setMethodCallHandler`：

```dart
methodChannel = MethodChannel(bridgeNameMethodChannel);
methodChannel.setMethodCallHandler((call) {
  print('got a call from platform: ${call.method}, ${call.arguments}');//call.arguments即为传递的参数
  return null;
});
```

在HostApp上在你需要传递参数时invokeMethod一下
```java
methodChannel.invokeMethod(methodName, params, callback);
```

**Comment by liguobing** [comment]
多谢多谢，回头我试一下，太感谢了
